# Generated by Django 5.2.6 on 2025-10-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=250, verbose_name='Кратко')),
                ('usr_name', models.CharField(max_length=100, verbose_name='Опубликовал')),
                ('txt', models.TextField(verbose_name='Новость')),
                ('dat_pub', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
